### ISSUE TITLE
site gives a privacy error on chrome

### ISSUE THREAD

**Issue by TobiTenno** [dggriffin/warframeLFG#36]
![image](https://cloud.githubusercontent.com/assets/7128721/15452268/eaa5b2e4-1fad-11e6-9515-68f86f2b7dc3.png)

**Comment by dggriffin** [comment]
I've filed a ticket with my hosting provider over this issue, but unfortunately they are taking their time! Hoping this is resolved ASAP.

**Comment by dggriffin** [comment]
This should now be resolved.
